runtime: nodejs14

handlers:
    # Serve API calls with express
    - url: /api/v1/.*
      secure: always
      script: auto

    #  # Serve all static files with url ending with a file extension
    - url: /(.*\..+)$
      secure: always
      static_files: public/build/\1
      upload: public/build/(.*\..+)$

    # Catch all handler to index.html
    - url: /.*
      secure: always
      static_files: public/build/index.html
      upload: public/build/index.html